[package]
name = "naver-fe-news-feed"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
comrak = "0.11"
atom_syndication = "0.10"
html-escape = "0.2.9"
